// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6gtHRKmD12dsqDG4slpjdpaLHQiQUZmM',
    appId: '1:816747500442:web:e0ce642482f84738062023',
    messagingSenderId: '816747500442',
    projectId: 'mmajunkie-c8756',
    authDomain: 'mmajunkie-c8756.firebaseapp.com',
    storageBucket: 'mmajunkie-c8756.appspot.com',
    measurementId: 'G-CLDWRNRTR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJJB-e9WLylYMR1unfFKdb4d3YXjlP-ck',
    appId: '1:816747500442:android:696f85d38b3d96dd062023',
    messagingSenderId: '816747500442',
    projectId: 'mmajunkie-c8756',
    storageBucket: 'mmajunkie-c8756.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmzmUqdtHbuOE-U9bAyyPXcJpOfrsDFq8',
    appId: '1:816747500442:ios:260b1e3059555e7a062023',
    messagingSenderId: '816747500442',
    projectId: 'mmajunkie-c8756',
    storageBucket: 'mmajunkie-c8756.appspot.com',
    iosClientId: '816747500442-eadtuuisd78euadn5gffcd2fgi3poebg.apps.googleusercontent.com',
    iosBundleId: 'la.nimble.mmajunkie',
  );
}
